# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modbus_tcp\ui\modbus_window.ui',
# licensing of 'modbus_tcp\ui\modbus_window.ui' applies.
#
# Created: Wed Oct  9 10:37:56 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(383, 421)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.relays_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.relays_groupBox.setGeometry(QtCore.QRect(240, 10, 131, 141))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.relays_groupBox.sizePolicy().hasHeightForWidth())
        self.relays_groupBox.setSizePolicy(sizePolicy)
        self.relays_groupBox.setObjectName("relays_groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.relays_groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 101, 88))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.relay_1_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.relay_1_checkBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.relay_1_checkBox.sizePolicy().hasHeightForWidth())
        self.relay_1_checkBox.setSizePolicy(sizePolicy)
        self.relay_1_checkBox.setObjectName("relay_1_checkBox")
        self.verticalLayout.addWidget(self.relay_1_checkBox)
        self.relay_2_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.relay_2_checkBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.relay_2_checkBox.sizePolicy().hasHeightForWidth())
        self.relay_2_checkBox.setSizePolicy(sizePolicy)
        self.relay_2_checkBox.setObjectName("relay_2_checkBox")
        self.verticalLayout.addWidget(self.relay_2_checkBox)
        self.relay_3_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.relay_3_checkBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.relay_3_checkBox.sizePolicy().hasHeightForWidth())
        self.relay_3_checkBox.setSizePolicy(sizePolicy)
        self.relay_3_checkBox.setObjectName("relay_3_checkBox")
        self.verticalLayout.addWidget(self.relay_3_checkBox)
        self.relay_4_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.relay_4_checkBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.relay_4_checkBox.sizePolicy().hasHeightForWidth())
        self.relay_4_checkBox.setSizePolicy(sizePolicy)
        self.relay_4_checkBox.setObjectName("relay_4_checkBox")
        self.verticalLayout.addWidget(self.relay_4_checkBox)
        self.modbus_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.modbus_groupBox.setGeometry(QtCore.QRect(10, 10, 221, 141))
        self.modbus_groupBox.setObjectName("modbus_groupBox")
        self.widget = QtWidgets.QWidget(self.modbus_groupBox)
        self.widget.setGeometry(QtCore.QRect(10, 20, 201, 109))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mater_ip_label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mater_ip_label.sizePolicy().hasHeightForWidth())
        self.mater_ip_label.setSizePolicy(sizePolicy)
        self.mater_ip_label.setObjectName("mater_ip_label")
        self.horizontalLayout.addWidget(self.mater_ip_label)
        self.master_ip_lineEdit = QtWidgets.QLineEdit(self.widget)
        self.master_ip_lineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.master_ip_lineEdit.sizePolicy().hasHeightForWidth())
        self.master_ip_lineEdit.setSizePolicy(sizePolicy)
        self.master_ip_lineEdit.setObjectName("master_ip_lineEdit")
        self.horizontalLayout.addWidget(self.master_ip_lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.slave_ip_label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slave_ip_label.sizePolicy().hasHeightForWidth())
        self.slave_ip_label.setSizePolicy(sizePolicy)
        self.slave_ip_label.setObjectName("slave_ip_label")
        self.horizontalLayout_2.addWidget(self.slave_ip_label)
        self.slave_ip_lineEdit = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slave_ip_lineEdit.sizePolicy().hasHeightForWidth())
        self.slave_ip_lineEdit.setSizePolicy(sizePolicy)
        self.slave_ip_lineEdit.setObjectName("slave_ip_lineEdit")
        self.horizontalLayout_2.addWidget(self.slave_ip_lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.port_label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.port_label.sizePolicy().hasHeightForWidth())
        self.port_label.setSizePolicy(sizePolicy)
        self.port_label.setObjectName("port_label")
        self.horizontalLayout_3.addWidget(self.port_label)
        self.port_lineEdit = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.port_lineEdit.sizePolicy().hasHeightForWidth())
        self.port_lineEdit.setSizePolicy(sizePolicy)
        self.port_lineEdit.setObjectName("port_lineEdit")
        self.horizontalLayout_3.addWidget(self.port_lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.connect_button = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connect_button.sizePolicy().hasHeightForWidth())
        self.connect_button.setSizePolicy(sizePolicy)
        self.connect_button.setObjectName("connect_button")
        self.verticalLayout_2.addWidget(self.connect_button)
        self.inspect_comunication_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.inspect_comunication_groupBox.setGeometry(QtCore.QRect(9, 159, 361, 221))
        self.inspect_comunication_groupBox.setObjectName("inspect_comunication_groupBox")
        self.communication_inspector_textEdit = QtWidgets.QPlainTextEdit(self.inspect_comunication_groupBox)
        self.communication_inspector_textEdit.setEnabled(False)
        self.communication_inspector_textEdit.setGeometry(QtCore.QRect(10, 20, 341, 191))
        self.communication_inspector_textEdit.setObjectName("communication_inspector_textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 383, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Modbus TCP", None, -1))
        self.relays_groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Relays [ON/OFF]", None, -1))
        self.relay_1_checkBox.setText(QtWidgets.QApplication.translate("MainWindow", "Relay 1", None, -1))
        self.relay_2_checkBox.setText(QtWidgets.QApplication.translate("MainWindow", "Relay 2", None, -1))
        self.relay_3_checkBox.setText(QtWidgets.QApplication.translate("MainWindow", "Relay 3", None, -1))
        self.relay_4_checkBox.setText(QtWidgets.QApplication.translate("MainWindow", "Relay 4", None, -1))
        self.modbus_groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Modbus configure", None, -1))
        self.mater_ip_label.setText(QtWidgets.QApplication.translate("MainWindow", "Master IP :", None, -1))
        self.slave_ip_label.setText(QtWidgets.QApplication.translate("MainWindow", "Slave IP :", None, -1))
        self.port_label.setText(QtWidgets.QApplication.translate("MainWindow", "Port :", None, -1))
        self.port_lineEdit.setText(QtWidgets.QApplication.translate("MainWindow", "552", None, -1))
        self.connect_button.setText(QtWidgets.QApplication.translate("MainWindow", "Connect", None, -1))
        self.inspect_comunication_groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Inspect comunication", None, -1))

